package mementoPattern;

public enum ChessPieces {


    BQUEEN, WQUEEN, BKING, WKING, BBISHOPL, BBISHOPR,
    WBISHOPL, WBISHOPR, BKNIGHTL, BKNIGHTR, WKNIGHTL,
    WKNIGHTR, BROOKL, BROOKR,
    WROOKL, WROOKR, WPAWN, BPAWN, BLANK;

}
